name: e2e
on: [push]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Install dependencies
        run: npm install
      - name: E2E
        run: npm run e2e
